spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:
                url: jdbc:mysql://172.31.203.5:3306/mc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: 15987532
            second:
                url: jdbc:mysql://172.31.203.5:3306/mc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: 15987532
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    activemq:
      broker-url: tcp://127.0.0.1:61616
      user: admin
      password: admin
    jms:
      pub-sub-domain: true
    redis:
            host: 172.31.203.4
            port: 6379
            password: 15987532
            pool:
              max-active: 8
              max-idle: 8000
              min-idle: 100
              max-wait: 10000